name: Cloudflare IP 优选 + 华为云 DNS 更新

on:
  schedule:
    - cron: '0 */1 * * *' # 每小时运行一次
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  update_dns:
    runs-on: ubuntu-latest
    env:
      DOMAIN: cdn.orgv.me
      SUBDOMAIN: cf
      HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
      HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
      HUAWEI_REGION: ap-southeast-1
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Python & 依赖
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 huaweicloudsdkcore huaweicloudsdkdns

      - name: 运行 Cloudflare IP 抓取 + 华为云 DNS 更新
        run: python cloudflare_dns_updater.py

      - name: 保存 JSON Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-ip-data
          path: cloudflare_bestip.json
          retention-days: 7
