name: Cloudflare IP & Huawei DNS Update bbbb

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  update_dns:
    runs-on: ubuntu-latest
    env:
      DOMAIN: cdn.orgv.me
      SUBDOMAIN: cf
      HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
      HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
      HUAWEI_REGION: ap-southeast-1

    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 huaweicloudsdkcore huaweicloudsdkdns

      - name: 运行 Cloudflare IP 抓取与 DNS 更新
        run: python cloudflare_dns_updater.py
