name: Cloudflare DNS Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次

jobs:
  update-dns:
    runs-on: ubuntu-latest

    env:
      OUTPUT_FILE: cloudflare_ips.json
      HUAWEI_PROJECT_ID: ${{ secrets.HUAWEI_PROJECT_ID }}
      HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
      HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
      DOMAIN: ${{ secrets.DOMAIN }}
      SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
      CT_A_ID: ${{ secrets.CT_A_ID }}
      CU_A_ID: ${{ secrets.CU_A_ID }}
      CM_A_ID: ${{ secrets.CM_A_ID }}
      CT_AAAA_ID: ${{ secrets.CT_AAAA_ID }}
      CU_AAAA_ID: ${{ secrets.CU_AAAA_ID }}
      CM_AAAA_ID: ${{ secrets.CM_AAAA_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Initialize Go module
        run: |
          if [ ! -f go.mod ]; then
            go mod init cloudflare-dns-updater
          fi

      - name: Download dependencies and generate go.sum
        run: go mod tidy

      - name: Build Go binary
        run: go build -o cloudflare_fetch main.go

      - name: Run Cloudflare fetch & Huawei DNS update
        run: ./cloudflare_fetch

      - name: Commit updated cloudflare_ips.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cloudflare_ips.json
          git commit -m "Update cloudflare_ips.json [skip ci]" || echo "No changes to commit"
          git push
