name: Cloudflare DNS Update

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:

jobs:
  update-dns:
    runs-on: ubuntu-latest
    env:
      HUAWEI_PROJECT_ID: ${{ secrets.HUAWEI_PROJECT_ID }}
      HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
      HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
      HUAWEI_REGION: ap-southeast-1
      ZONE_ID: ${{ secrets.ZONE_ID }}
      DOMAIN: ${{ secrets.DOMAIN }}
      SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
      CT_A_ID: ${{ secrets.CT_A_ID }}
      CU_A_ID: ${{ secrets.CU_A_ID }}
      CM_A_ID: ${{ secrets.CM_A_ID }}
      CT_AAAA_ID: ${{ secrets.CT_AAAA_ID }}
      CU_AAAA_ID: ${{ secrets.CU_AAAA_ID }}
      CM_AAAA_ID: ${{ secrets.CM_AAAA_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Initialize Go modules
        run: |
          go mod init cloudflare-dns || true
          go get github.com/huaweicloud/huaweicloud-sdk-go-v3@v0.1.165

      - name: Build Go binary
        run: |
          go build -o cloudflare_fetch main.go

      - name: Run Cloudflare fetch & Huawei DNS update
        run: |
          ./cloudflare_fetch

      - name: Commit cloudflare_ips.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cloudflare_ips.json
          git diff --cached --quiet || git commit -m "更新 cloudflare_ips.json [skip ci]"
          git push
