name: Cloudflare IP 抓取并更新华为云 DNS

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: 初始化 go.mod（如无）
        run: |
          if [ ! -f go.mod ]; then
            go mod init cloudflare-dns-updater
          fi

      - name: 安装依赖
        run: |
          go mod tidy
          go mod download

      - name: 编译程序
        run: go build -o cloudflare_fetch cloudflare_fetch.go

      - name: 执行抓取并更新 DNS
        env:
          HUAWEI_PROJECT_ID: ${{ secrets.HUAWEI_PROJECT_ID }}
          HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
          HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
          HUAWEI_ZONE_ID: ${{ secrets.HUAWEI_ZONE_ID }}
          HUAWEI_DOMAIN: ${{ secrets.HUAWEI_DOMAIN }}
          HUAWEI_SUBDOMAIN: ${{ secrets.HUAWEI_SUBDOMAIN }}
          HUAWEI_CT_A_ID: ${{ secrets.HUAWEI_CT_A_ID }}
          HUAWEI_CU_A_ID: ${{ secrets.HUAWEI_CU_A_ID }}
          HUAWEI_CM_A_ID: ${{ secrets.HUAWEI_CM_A_ID }}
        run: ./cloudflare_fetch
