name: Update Huawei Cloud DNS from Cloudflare IP

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write    # 允许提交 go.sum 变更

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 保留 Git 凭据

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Generate go.sum if missing
        run: |
          if [ ! -f go.sum ]; then
            echo "go.sum 不存在，自动生成..."
          else
            echo "go.sum 已存在，将进行更新..."
          fi
          go mod tidy

      - name: Commit and push go.sum changes (if any)
        run: |
          if [ -n "$(git status --porcelain go.sum)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add go.sum
            git commit -m "Auto-generate go.sum"
            git push
          else
            echo "go.sum 无需更新"
          fi

      - name: Build Go binary
        run: go build -o cloudflare_fetch cloudflare_fetch.go

      - name: Run DNS update
        env:
          HUAWEI_PROJECT_ID: ${{ secrets.HUAWEI_PROJECT_ID }}
          HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
          HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
        run: ./cloudflare_fetch
