name: Cloudflare IP抓取并更新华为云DNS

on:
  schedule:
    - cron: '*/30 * * * *' # 每 30 分钟执行一次
  workflow_dispatch:

jobs:
  update-dns:
    runs-on: ubuntu-latest

    env:
      OUTPUT_FILE: cloudflare_ips.json
      HUAWEI_PROJECT_ID: ${{ secrets.HUAWEI_PROJECT_ID }}
      HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
      HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
      DOMAIN: ${{ secrets.DOMAIN }}
      SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
      CT_A_ID: ${{ secrets.CT_A_ID }}
      CU_A_ID: ${{ secrets.CU_A_ID }}
      CM_A_ID: ${{ secrets.CM_A_ID }}
      CT_AAAA_ID: ${{ secrets.CT_AAAA_ID }}
      CU_AAAA_ID: ${{ secrets.CU_AAAA_ID }}
      CM_AAAA_ID: ${{ secrets.CM_AAAA_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Go binary
        run: go build -o cloudflare_fetch main.go

      - name: Run Cloudflare IP fetch & Huawei DNS update
        run: ./cloudflare_fetch

      - name: Commit cloudflare_ips.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $OUTPUT_FILE
          git commit -m "Update cloudflare_ips.json [skip ci]" || echo "No changes to commit"
          git push origin HEAD
