name: Update Huawei Cloud DNS from Cloudflare IP

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Ensure go.mod exists
        run: |
          if [ ! -f go.mod ]; then
            echo "未检测到 go.mod，自动初始化..."
            go mod init cloudflare-dns-updater
          fi

      - name: Generate go.sum
        run: |
          go mod tidy

      - name: Commit and push go.sum changes (if any)
        run: |
          if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add go.mod go.sum
            git commit -m "Auto-generate go.mod and go.sum"
            git push
          else
            echo "go.mod / go.sum 无需更新"
          fi

      - name: Build Go binary
        run: go build -o cloudflare_fetch cloudflare_fetch.go

      - name: Run DNS update
        env:
          HUAWEI_PROJECT_ID: ${{ secrets.HUAWEI_PROJECT_ID }}
          HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
          HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
        run: ./cloudflare_fetch
