name: Cloudflare DNS Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次，可自定义

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: 初始化模块 & 下载依赖
        run: |
          go mod tidy   # 自动生成 go.sum 并下载所有依赖

      - name: 构建可执行文件
        run: |
          go build -o cloudflare_fetch main.go

      - name: 运行程序
        env:
          HUAWEI_PROJECT_ID: ${{ secrets.HUAWEI_PROJECT_ID }}
          HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
          HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
          DOMAIN: ${{ secrets.DOMAIN }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          CT_A_ID: ${{ secrets.CT_A_ID }}
          CU_A_ID: ${{ secrets.CU_A_ID }}
          CM_A_ID: ${{ secrets.CM_A_ID }}
          CT_AAAA_ID: ${{ secrets.CT_AAAA_ID }}
          CU_AAAA_ID: ${{ secrets.CU_AAAA_ID }}
          CM_AAAA_ID: ${{ secrets.CM_AAAA_ID }}
        run: |
          ./cloudflare_fetch

      - name: Commit cloudflare_ips.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cloudflare_ips.json
          git diff --cached --quiet || git commit -m "更新 cloudflare_ips.json [skip ci]"
          git push
